INSERT INTO CLIENTES (IDCLIENTE, NOME, LOGO_URL) VALUES
	(1, 'INSTRUÇÕES GERAIS', '/assets/images/icons_clientes/geral.jpg'),
	(2, 'ALELO', '/assets/images/icons_clientes/alelo.jpg'),
	(3, 'APPLE', '/assets/images/icons_clientes/apple.jpg'),
	(4, 'ASURION', '/assets/images/icons_clientes/asurion.jpg'),
	(5, 'C6 BANK', '/assets/images/icons_clientes/c6.jpg'),
	(6, 'BANCO CARREFOUR', '/assets/images/icons_clientes/banco_carrefour.jpg'),
	(7, 'BANCO DO BRASIL', '/assets/images/icons_clientes/bb.jpg'),
	(8, 'BANCO PAN', '/assets/images/icons_clientes/banco_pan.jpg'),
	(9, 'BANCO SAFRA', '/assets/images/icons_clientes/safra.jpg'),
	(10, 'BANCO SOFISA', '/assets/images/icons_clientes/sofisa.jpg'),
	(11, 'BEMATECH', '/assets/images/icons_clientes/bematech.jpg'),
	(12, 'BENEFICIO FACIL', '/assets/images/icons_clientes/beneficiofacil.jpg'),
	(13, 'BMB', '/assets/images/icons_clientes/bmb.jpg'),
	(14, 'BMG', '/assets/images/icons_clientes/bmg.jpg'),
	(15, 'BOTICARIO', '/assets/images/icons_clientes/boticario.jpg'),
	(16, 'BRADESCO', '/assets/images/icons_clientes/bradesco.jpg'),
	(17, 'BURGER KING', '/assets/images/icons_clientes/bk.jpg'),
	(18, 'CAIXA SEGURADORA', '/assets/images/icons_clientes/caixa_seguradora.jpg'),
	(19, 'CATENO', '/assets/images/icons_clientes/cateno.jpg'),
	(20, 'CETELEM', '/assets/images/icons_clientes/cetelem.jpg'),
	(21, 'CIELO', '/assets/images/icons_clientes/cielo.jpg'),
	(22, 'CLARO', '/assets/images/icons_clientes/claro.jpg'),
	(23, 'CONECTCAR', '/assets/images/icons_clientes/connectcar.jpg'),
	(24, 'CONSULTING HOUSE', '/assets/images/icons_clientes/ch.jpg'),
	(25, 'CTF', '/assets/images/icons_clientes/ctf.jpg'),
	(26, 'DASA', '/assets/images/icons_clientes/dasa.jpg'),
	(27, 'DECOLAR', '/assets/images/icons_clientes/decolar.jpg'),
	(28, 'DEMAIS AREAS', '/assets/images/icons_clientes/demais_aereas.jpg'),
	(29, 'DISNEY', '/assets/images/icons_clientes/disney.jpg'),
	(30, 'EASYNVEST', '/assets/images/icons_clientes/easynvest.jpg'),
	(31, 'EDP', '/assets/images/icons_clientes/edp.jpg'),
	(32, 'EDITORA GLOBO', '/assets/images/icons_clientes/editora_globo.jpg'),
	(33, 'ENEL', '/assets/images/icons_clientes/enel.jpg'),
	(34, 'FACEBOOK', '/assets/images/icons_clientes/facebook.jpg'),
	(35, 'FIAT', '/assets/images/icons_clientes/fiat.jpg'),
	(36, 'FIRST DATA', '/assets/images/icons_clientes/firstdata.jpg'),
	(37, 'FORD BRASIL', '/assets/images/icons_clientes/ford.jpg'),
	(38, 'GOOGLE BRASIL', '/assets/images/icons_clientes/google.jpg'),
	(39, 'GPA', '/assets/images/icons_clientes/gpa.jpg'),
	(40, 'GRUPO ALIANCA', '/assets/images/icons_clientes/grupo_alianca.jpg'),
	(42, 'HONG', '/assets/images/icons_clientes/hong.jpg'),
	(43, 'HUAWEI', '/assets/images/icons_clientes/huawei.jpg'),
	(44, 'ICATU', '/assets/images/icons_clientes/icatu.jpg'),
	(45, 'IFOOD', '/assets/images/icons_clientes/ifood.jpg'),
	(46, 'INTERMEDICA', '/assets/images/icons_clientes/intermedica.jpg'),
	(47, 'INTERODONTO', '/assets/images/icons_clientes/interodonto.jpg'),
	(48, 'ITAU', '/assets/images/icons_clientes/itau.jpg'),
	(49, 'KROTON', '/assets/images/icons_clientes/kroton.jpg'),
	(50, 'LENOVO', '/assets/images/icons_clientes/lenovo.jpg'),
	(51, 'LIVELO', '/assets/images/icons_clientes/livelo.jpg'),
	(52, 'LOSANGO', '/assets/images/icons_clientes/losango.jpg'),
	(53, 'MARISA', '/assets/images/icons_clientes/marisa.jpg'),
	(54, 'MERCADO PAGO', '/assets/images/icons_clientes/mercadopago.jpg'),
	(55, 'MOTOROLA', '/assets/images/icons_clientes/motorola.jpg'),
	(56, 'NESTLE', '/assets/images/icons_clientes/nestle.jpg'),
	(57, 'OI', '/assets/images/icons_clientes/oi.jpg'),
	(58, 'PEUGEOT', '/assets/images/icons_clientes/pegeout.jpg'),
	(59, 'PRAVALER', '/assets/images/icons_clientes/pravaler.jpg'),
	(60, 'QUALICORP', '/assets/images/icons_clientes/qualicorp.jpg'),
	(61, 'QUINTO ANDAR', '/assets/images/icons_clientes/quintoandar.jpg'),
	(62, 'RENNER', '/assets/images/icons_clientes/renner.jpg'),
	(63, 'RIOT GAMES', '/assets/images/icons_clientes/riotgames.jpg'),
	(64, 'SAMSUNG', '/assets/images/icons_clientes/samsung.jpg'),
	(65, 'SANTANDER', '/assets/images/icons_clientes/santander.jpg'),
	(66, 'SEM PARAR', '/assets/images/icons_clientes/semparar.jpg'),
	(67, 'SHELL', '/assets/images/icons_clientes/shell.jpg'),
	(68, 'SODEXO', '/assets/images/icons_clientes/sodexo.jpg'),
	(69, 'SONY', '/assets/images/icons_clientes/sony.jpg'),
	(70, 'STELO', '/assets/images/icons_clientes/stelo.jpg'),
	(71, 'SUL AMERICA CIA', '/assets/images/icons_clientes/sulamerica.jpg'),
	(72, 'TELEFONICA', '/assets/images/icons_clientes/telefonica.jpg'),
	(73, 'TIM', '/assets/images/icons_clientes/tim.jpg'),
	(75, 'UNIDAS', '/assets/images/icons_clientes/unidas.jpg'),
	(76, 'UNILEVER', '/assets/images/icons_clientes/unilever.jpg'),
	(77, 'UNIMED BH', '/assets/images/icons_clientes/unimedbh.jpg'),
	(78, 'UNIMED FLORIANOPOLIS', '/assets/images/icons_clientes/unimedfloripa.jpg'),
	(79, 'UNIMED RJ', '/assets/images/icons_clientes/unimedrio.jpg'),
	(80, 'VELOE', '/assets/images/icons_clientes/veloe.jpg'),
	(81, 'VIA VAREJO', '/assets/images/icons_clientes/viavarejo.jpg'),
	(82, 'VIVO', '/assets/images/icons_clientes/vivo.jpg'),
	(83, 'WHITE MARTINS BRASIL', '/assets/images/icons_clientes/whitemartins.jpg'),
	(84, 'XP INVESTIMENTOS', '/assets/images/icons_clientes/xp.jpg'),
	(86, 'Fleury', '/assets/images/icons_clientes/fleury.jpg'),
	(87, 'Carrefour', '/assets/images/icons_clientes/carrefour.jpg'),
	(88, 'Froneri', '/assets/images/icons_clientes/froneri.jpg'),
	(89, 'UNIMED', '/assets/images/icons_clientes/unimed.jpg'),
	(91, 'UNIMED PORTO ALEGRE', '/assets/images/icons_clientes/unimedpoa.jpg'),
	(92, '3M', '/assets/images/icons_clientes/3m.jpg'),
	(93, 'JCA', '/assets/images/icons_clientes/jca.jpg');
