ALTER TABLE USUARIOS
MODIFY COLUMN CARGO VARCHAR(100);

ALTER TABLE USUARIOS
MODIFY COLUMN EMAIL VARCHAR(100);

ALTER TABLE MAPA_OPERACIONAL
MODIFY COLUMN VLAN_DADOS LONGTEXT;

ALTER TABLE MAPA_OPERACIONAL
MODIFY COLUMN VLAN_VOZ LONGTEXT;

INSERT INTO CLIENTES (IDCLIENTE, NOME, LOGO_URL) VALUES
	(41, 'OLIST', '/assets/images/icons_clientes/olist.jpg');
INSERT INTO CLIENTES (IDCLIENTE, NOME, LOGO_URL) VALUES
	(74, 'MARINER', '/assets/images/icons_clientes/mariner.jpg');
INSERT INTO CLIENTES (IDCLIENTE, NOME, LOGO_URL) VALUES
	(85, 'BANCO DLL', '/assets/images/icons_clientes/bancodll.jpg');


