INSERT INTO DOMINIOS (IDDOMINIO, NOME) VALUES
	(1, 'ATENTOBR'),
	(2, 'ACIELO'),
	(3, 'AFACEBOOKBR'),
	(4, 'APOIOCASASBAHIA'),
	(5, 'ICATU-ATENTO'),
	(6, 'ARENNERBR'),
	(7, 'ITAUATENTOBR'),
	(8, 'AINTERMEDICA'),
	(9, 'CLIENTEAPBR'),
	(10, 'RECOVERYBR');
