CREATE TABLE LOGS (
  IDUSUARIO INT(11) NOT NULL,
  LOGIN_NT VARCHAR(100) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ACTION VARCHAR(100) NOT NULL,
  DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);