CREATE TABLE LOGS (
  IDUSUARIO INT(11) NOT NULL,
  LOGIN_NT VARCHAR(100) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ACTION LONGTEXT NOT NULL,
  DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE SESSIONS (
  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ID_USUARIO INT(11) NOT NULL,
  TOKEN LONGTEXT NOT NULL,
    DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()

);


ALTER TABLE SESSIONS
ADD CONSTRAINT FK_USER_SESSION
FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIOS(IDUSUARIO);

